apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app-live-view
    apps.tanzu.vmware.com/workload-type: web
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.name: tanzu-java-web-app-live-view
spec:
  params:
  - name: annotations
    value:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/themapisto/tanzu-java-web-app2
